
#Parameters:
#  MyKeyName:
#    Type: String

Resources:

  MyEC2Instance:
    Type: AWS::EC2::Instance

    Properties:
      InstanceType: t2.micro
      ImageId: ami-00aa9d3df94c6c354

      #KeyName: !Ref MyKeyName
      KeyName: demo1
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: DemoCF

      UserData:
        Fn::Base64: |
          #!/bin/bash
          cat > ~/file <<EOF
          Hello World
          EOF

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
Outputs:
  InstanceID:
    Description: InstanceID
    Value: !Ref MyEC2Instance
